# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desig.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ventanaPrincipal(object):
    def setupUi(self, ventanaPrincipal):
        ventanaPrincipal.setObjectName("ventanaPrincipal")
        ventanaPrincipal.resize(726, 316)
        self.pestanaPrincipal = QtWidgets.QTabWidget(ventanaPrincipal)
        self.pestanaPrincipal.setGeometry(QtCore.QRect(10, 10, 711, 301))
        self.pestanaPrincipal.setObjectName("pestanaPrincipal")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label.setObjectName("label")
        self.dato1Perm = QtWidgets.QLineEdit(self.tab)
        self.dato1Perm.setGeometry(QtCore.QRect(10, 40, 51, 20))
        self.dato1Perm.setObjectName("dato1Perm")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 121, 16))
        self.label_2.setObjectName("label_2")
        self.resultadoPermutacion = QtWidgets.QLineEdit(self.tab)
        self.resultadoPermutacion.setEnabled(False)
        self.resultadoPermutacion.setGeometry(QtCore.QRect(10, 100, 301, 111))
        self.resultadoPermutacion.setAcceptDrops(True)
        self.resultadoPermutacion.setObjectName("resultadoPermutacion")
        self.botonLimpiarPermutacion = QtWidgets.QPushButton(self.tab)
        self.botonLimpiarPermutacion.setGeometry(QtCore.QRect(320, 100, 75, 23))
        self.botonLimpiarPermutacion.setObjectName("botonLimpiarPermutacion")
        self.botonCalcularPermutacion = QtWidgets.QPushButton(self.tab)
        self.botonCalcularPermutacion.setGeometry(QtCore.QRect(320, 40, 75, 23))
        self.botonCalcularPermutacion.setObjectName("botonCalcularPermutacion")
        self.dato2Perm = QtWidgets.QLineEdit(self.tab)
        self.dato2Perm.setGeometry(QtCore.QRect(70, 40, 51, 20))
        self.dato2Perm.setObjectName("dato2Perm")
        self.dato3Perm = QtWidgets.QLineEdit(self.tab)
        self.dato3Perm.setGeometry(QtCore.QRect(130, 40, 51, 20))
        self.dato3Perm.setObjectName("dato3Perm")
        self.dato4Perm = QtWidgets.QLineEdit(self.tab)
        self.dato4Perm.setGeometry(QtCore.QRect(190, 40, 51, 20))
        self.dato4Perm.setObjectName("dato4Perm")
        self.dato5Perm = QtWidgets.QLineEdit(self.tab)
        self.dato5Perm.setGeometry(QtCore.QRect(250, 40, 51, 20))
        self.dato5Perm.setObjectName("dato5Perm")
        self.pestanaPrincipal.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 131, 16))
        self.label_3.setObjectName("label_3")
        self.datoFact = QtWidgets.QLineEdit(self.tab_2)
        self.datoFact.setGeometry(QtCore.QRect(20, 30, 131, 20))
        self.datoFact.setObjectName("datoFact")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 81, 16))
        self.label_4.setObjectName("label_4")
        self.resultadoFactorial = QtWidgets.QLineEdit(self.tab_2)
        self.resultadoFactorial.setEnabled(False)
        self.resultadoFactorial.setGeometry(QtCore.QRect(20, 80, 131, 20))
        self.resultadoFactorial.setObjectName("resultadoFactorial")
        self.botonCalcularFactorial = QtWidgets.QPushButton(self.tab_2)
        self.botonCalcularFactorial.setGeometry(QtCore.QRect(180, 30, 75, 23))
        self.botonCalcularFactorial.setObjectName("botonCalcularFactorial")
        self.botonLimpiarFactorial = QtWidgets.QPushButton(self.tab_2)
        self.botonLimpiarFactorial.setGeometry(QtCore.QRect(180, 80, 75, 23))
        self.botonLimpiarFactorial.setObjectName("botonLimpiarFactorial")
        self.pestanaPrincipal.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.dato1Comb = QtWidgets.QLineEdit(self.tab_3)
        self.dato1Comb.setGeometry(QtCore.QRect(10, 30, 51, 20))
        self.dato1Comb.setObjectName("dato1Comb")
        self.botonCalcularCombinacion = QtWidgets.QPushButton(self.tab_3)
        self.botonCalcularCombinacion.setGeometry(QtCore.QRect(320, 30, 75, 23))
        self.botonCalcularCombinacion.setObjectName("botonCalcularCombinacion")
        self.dato4Comb = QtWidgets.QLineEdit(self.tab_3)
        self.dato4Comb.setGeometry(QtCore.QRect(190, 30, 51, 20))
        self.dato4Comb.setObjectName("dato4Comb")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 121, 16))
        self.label_5.setObjectName("label_5")
        self.resultadoCombinacion = QtWidgets.QLineEdit(self.tab_3)
        self.resultadoCombinacion.setEnabled(False)
        self.resultadoCombinacion.setGeometry(QtCore.QRect(10, 90, 301, 121))
        self.resultadoCombinacion.setObjectName("resultadoCombinacion")
        self.dato2Comb = QtWidgets.QLineEdit(self.tab_3)
        self.dato2Comb.setGeometry(QtCore.QRect(70, 30, 51, 20))
        self.dato2Comb.setObjectName("dato2Comb")
        self.botonLimpiarCombinacion = QtWidgets.QPushButton(self.tab_3)
        self.botonLimpiarCombinacion.setGeometry(QtCore.QRect(320, 90, 75, 23))
        self.botonLimpiarCombinacion.setObjectName("botonLimpiarCombinacion")
        self.dato5Comb = QtWidgets.QLineEdit(self.tab_3)
        self.dato5Comb.setGeometry(QtCore.QRect(250, 30, 51, 20))
        self.dato5Comb.setObjectName("dato5Comb")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label_6.setObjectName("label_6")
        self.dato3Comb = QtWidgets.QLineEdit(self.tab_3)
        self.dato3Comb.setGeometry(QtCore.QRect(130, 30, 51, 20))
        self.dato3Comb.setObjectName("dato3Comb")
        self.pestanaPrincipal.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.lista1Dato3Union = QtWidgets.QLineEdit(self.tab_4)
        self.lista1Dato3Union.setGeometry(QtCore.QRect(130, 30, 51, 20))
        self.lista1Dato3Union.setObjectName("lista1Dato3Union")
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.label_7.setObjectName("label_7")
        self.lista1Dato1Union = QtWidgets.QLineEdit(self.tab_4)
        self.lista1Dato1Union.setGeometry(QtCore.QRect(10, 30, 51, 20))
        self.lista1Dato1Union.setObjectName("lista1Dato1Union")
        self.lista1Dato5Union = QtWidgets.QLineEdit(self.tab_4)
        self.lista1Dato5Union.setGeometry(QtCore.QRect(250, 30, 51, 20))
        self.lista1Dato5Union.setObjectName("lista1Dato5Union")
        self.lista1Dato4Union = QtWidgets.QLineEdit(self.tab_4)
        self.lista1Dato4Union.setGeometry(QtCore.QRect(190, 30, 51, 20))
        self.lista1Dato4Union.setObjectName("lista1Dato4Union")
        self.lista1Dato2Union = QtWidgets.QLineEdit(self.tab_4)
        self.lista1Dato2Union.setGeometry(QtCore.QRect(70, 30, 51, 20))
        self.lista1Dato2Union.setObjectName("lista1Dato2Union")
        self.lista2Dato3Union = QtWidgets.QLineEdit(self.tab_4)
        self.lista2Dato3Union.setGeometry(QtCore.QRect(130, 80, 51, 20))
        self.lista2Dato3Union.setObjectName("lista2Dato3Union")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.label_8.setObjectName("label_8")
        self.lista2Dato1Union = QtWidgets.QLineEdit(self.tab_4)
        self.lista2Dato1Union.setGeometry(QtCore.QRect(10, 80, 51, 20))
        self.lista2Dato1Union.setObjectName("lista2Dato1Union")
        self.lista2Dato5Union = QtWidgets.QLineEdit(self.tab_4)
        self.lista2Dato5Union.setGeometry(QtCore.QRect(250, 80, 51, 20))
        self.lista2Dato5Union.setObjectName("lista2Dato5Union")
        self.botonCalcularUnion = QtWidgets.QPushButton(self.tab_4)
        self.botonCalcularUnion.setGeometry(QtCore.QRect(320, 50, 75, 23))
        self.botonCalcularUnion.setObjectName("botonCalcularUnion")
        self.lista2Dato4Union = QtWidgets.QLineEdit(self.tab_4)
        self.lista2Dato4Union.setGeometry(QtCore.QRect(190, 80, 51, 20))
        self.lista2Dato4Union.setObjectName("lista2Dato4Union")
        self.lista2Dato2Union = QtWidgets.QLineEdit(self.tab_4)
        self.lista2Dato2Union.setGeometry(QtCore.QRect(70, 80, 51, 20))
        self.lista2Dato2Union.setObjectName("lista2Dato2Union")
        self.botonLimpiarUnion = QtWidgets.QPushButton(self.tab_4)
        self.botonLimpiarUnion.setGeometry(QtCore.QRect(320, 140, 75, 23))
        self.botonLimpiarUnion.setObjectName("botonLimpiarUnion")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(10, 120, 71, 16))
        self.label_9.setObjectName("label_9")
        self.resultadoUnion = QtWidgets.QLineEdit(self.tab_4)
        self.resultadoUnion.setEnabled(False)
        self.resultadoUnion.setGeometry(QtCore.QRect(10, 140, 301, 101))
        self.resultadoUnion.setObjectName("resultadoUnion")
        self.pestanaPrincipal.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.lista1Dato3Intersec = QtWidgets.QLineEdit(self.tab_5)
        self.lista1Dato3Intersec.setGeometry(QtCore.QRect(130, 30, 51, 20))
        self.lista1Dato3Intersec.setObjectName("lista1Dato3Intersec")
        self.botonLimpiarInterseccion = QtWidgets.QPushButton(self.tab_5)
        self.botonLimpiarInterseccion.setGeometry(QtCore.QRect(320, 140, 75, 23))
        self.botonLimpiarInterseccion.setObjectName("botonLimpiarInterseccion")
        self.lista1Dato5Intersec = QtWidgets.QLineEdit(self.tab_5)
        self.lista1Dato5Intersec.setGeometry(QtCore.QRect(250, 30, 51, 20))
        self.lista1Dato5Intersec.setObjectName("lista1Dato5Intersec")
        self.lista1Dato2Intersec = QtWidgets.QLineEdit(self.tab_5)
        self.lista1Dato2Intersec.setGeometry(QtCore.QRect(70, 30, 51, 20))
        self.lista1Dato2Intersec.setObjectName("lista1Dato2Intersec")
        self.lista2Dato5Intersec = QtWidgets.QLineEdit(self.tab_5)
        self.lista2Dato5Intersec.setGeometry(QtCore.QRect(250, 80, 51, 20))
        self.lista2Dato5Intersec.setObjectName("lista2Dato5Intersec")
        self.resultadoInterseccion = QtWidgets.QLineEdit(self.tab_5)
        self.resultadoInterseccion.setEnabled(False)
        self.resultadoInterseccion.setGeometry(QtCore.QRect(10, 140, 301, 101))
        self.resultadoInterseccion.setObjectName("resultadoInterseccion")
        self.lista2Dato2Intersec = QtWidgets.QLineEdit(self.tab_5)
        self.lista2Dato2Intersec.setGeometry(QtCore.QRect(70, 80, 51, 20))
        self.lista2Dato2Intersec.setObjectName("lista2Dato2Intersec")
        self.label_10 = QtWidgets.QLabel(self.tab_5)
        self.label_10.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.label_10.setObjectName("label_10")
        self.lista1Dato1Intersec = QtWidgets.QLineEdit(self.tab_5)
        self.lista1Dato1Intersec.setGeometry(QtCore.QRect(10, 30, 51, 20))
        self.lista1Dato1Intersec.setObjectName("lista1Dato1Intersec")
        self.lista1Dato4Intersec = QtWidgets.QLineEdit(self.tab_5)
        self.lista1Dato4Intersec.setGeometry(QtCore.QRect(190, 30, 51, 20))
        self.lista1Dato4Intersec.setObjectName("lista1Dato4Intersec")
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        self.label_11.setGeometry(QtCore.QRect(10, 120, 101, 16))
        self.label_11.setObjectName("label_11")
        self.botonCalcularInterseccion = QtWidgets.QPushButton(self.tab_5)
        self.botonCalcularInterseccion.setGeometry(QtCore.QRect(320, 50, 75, 23))
        self.botonCalcularInterseccion.setObjectName("botonCalcularInterseccion")
        self.lista2Dato4Intersec = QtWidgets.QLineEdit(self.tab_5)
        self.lista2Dato4Intersec.setGeometry(QtCore.QRect(190, 80, 51, 20))
        self.lista2Dato4Intersec.setObjectName("lista2Dato4Intersec")
        self.label_12 = QtWidgets.QLabel(self.tab_5)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.label_12.setObjectName("label_12")
        self.lista2Dato3Intersec = QtWidgets.QLineEdit(self.tab_5)
        self.lista2Dato3Intersec.setGeometry(QtCore.QRect(130, 80, 51, 20))
        self.lista2Dato3Intersec.setObjectName("lista2Dato3Intersec")
        self.lista2Dato1Intersec = QtWidgets.QLineEdit(self.tab_5)
        self.lista2Dato1Intersec.setGeometry(QtCore.QRect(10, 80, 51, 20))
        self.lista2Dato1Intersec.setObjectName("lista2Dato1Intersec")
        self.pestanaPrincipal.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.botonCalcularDiferencia = QtWidgets.QPushButton(self.tab_6)
        self.botonCalcularDiferencia.setGeometry(QtCore.QRect(320, 50, 75, 23))
        self.botonCalcularDiferencia.setObjectName("botonCalcularDiferencia")
        self.label_25 = QtWidgets.QLabel(self.tab_6)
        self.label_25.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_25.setObjectName("label_25")
        self.lista2Dato1Difer = QtWidgets.QLineEdit(self.tab_6)
        self.lista2Dato1Difer.setGeometry(QtCore.QRect(10, 80, 51, 20))
        self.lista2Dato1Difer.setObjectName("lista2Dato1Difer")
        self.label_26 = QtWidgets.QLabel(self.tab_6)
        self.label_26.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.label_26.setObjectName("label_26")
        self.lista1Dato1Difer = QtWidgets.QLineEdit(self.tab_6)
        self.lista1Dato1Difer.setGeometry(QtCore.QRect(10, 30, 51, 20))
        self.lista1Dato1Difer.setObjectName("lista1Dato1Difer")
        self.label_27 = QtWidgets.QLabel(self.tab_6)
        self.label_27.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.label_27.setObjectName("label_27")
        self.botonLimpiarDiferencia = QtWidgets.QPushButton(self.tab_6)
        self.botonLimpiarDiferencia.setGeometry(QtCore.QRect(320, 140, 75, 23))
        self.botonLimpiarDiferencia.setObjectName("botonLimpiarDiferencia")
        self.lista2Dato2Difer = QtWidgets.QLineEdit(self.tab_6)
        self.lista2Dato2Difer.setGeometry(QtCore.QRect(70, 80, 51, 20))
        self.lista2Dato2Difer.setObjectName("lista2Dato2Difer")
        self.resultadoDiferencia = QtWidgets.QLineEdit(self.tab_6)
        self.resultadoDiferencia.setEnabled(False)
        self.resultadoDiferencia.setGeometry(QtCore.QRect(10, 140, 301, 101))
        self.resultadoDiferencia.setObjectName("resultadoDiferencia")
        self.lista1Dato3Difer = QtWidgets.QLineEdit(self.tab_6)
        self.lista1Dato3Difer.setGeometry(QtCore.QRect(130, 30, 51, 20))
        self.lista1Dato3Difer.setObjectName("lista1Dato3Difer")
        self.lista2Dato4Difer = QtWidgets.QLineEdit(self.tab_6)
        self.lista2Dato4Difer.setGeometry(QtCore.QRect(190, 80, 51, 20))
        self.lista2Dato4Difer.setObjectName("lista2Dato4Difer")
        self.lista1Dato5Difer = QtWidgets.QLineEdit(self.tab_6)
        self.lista1Dato5Difer.setGeometry(QtCore.QRect(250, 30, 51, 20))
        self.lista1Dato5Difer.setObjectName("lista1Dato5Difer")
        self.lista1Dato4Difer = QtWidgets.QLineEdit(self.tab_6)
        self.lista1Dato4Difer.setGeometry(QtCore.QRect(190, 30, 51, 20))
        self.lista1Dato4Difer.setObjectName("lista1Dato4Difer")
        self.lista1Dato2Difer = QtWidgets.QLineEdit(self.tab_6)
        self.lista1Dato2Difer.setGeometry(QtCore.QRect(70, 30, 51, 20))
        self.lista1Dato2Difer.setObjectName("lista1Dato2Difer")
        self.lista2Dato3Difer = QtWidgets.QLineEdit(self.tab_6)
        self.lista2Dato3Difer.setGeometry(QtCore.QRect(130, 80, 51, 20))
        self.lista2Dato3Difer.setObjectName("lista2Dato3Difer")
        self.lista2Dato5Difer = QtWidgets.QLineEdit(self.tab_6)
        self.lista2Dato5Difer.setGeometry(QtCore.QRect(250, 80, 51, 20))
        self.lista2Dato5Difer.setObjectName("lista2Dato5Difer")
        self.pestanaPrincipal.addTab(self.tab_6, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.dato1Potencia = QtWidgets.QLineEdit(self.tab_8)
        self.dato1Potencia.setGeometry(QtCore.QRect(10, 50, 51, 20))
        self.dato1Potencia.setObjectName("dato1Potencia")
        self.dato2Poteencia = QtWidgets.QLineEdit(self.tab_8)
        self.dato2Poteencia.setGeometry(QtCore.QRect(160, 50, 51, 20))
        self.dato2Poteencia.setObjectName("dato2Poteencia")
        self.label_28 = QtWidgets.QLabel(self.tab_8)
        self.label_28.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_28.setObjectName("label_28")
        self.resultadoPotencia = QtWidgets.QLineEdit(self.tab_8)
        self.resultadoPotencia.setEnabled(False)
        self.resultadoPotencia.setGeometry(QtCore.QRect(10, 130, 91, 20))
        self.resultadoPotencia.setObjectName("resultadoPotencia")
        self.label_29 = QtWidgets.QLabel(self.tab_8)
        self.label_29.setGeometry(QtCore.QRect(80, 50, 61, 16))
        self.label_29.setObjectName("label_29")
        self.botonCalcularPotencia = QtWidgets.QPushButton(self.tab_8)
        self.botonCalcularPotencia.setGeometry(QtCore.QRect(240, 50, 75, 23))
        self.botonCalcularPotencia.setObjectName("botonCalcularPotencia")
        self.botonLimpiarPotencia = QtWidgets.QPushButton(self.tab_8)
        self.botonLimpiarPotencia.setGeometry(QtCore.QRect(120, 130, 75, 23))
        self.botonLimpiarPotencia.setObjectName("botonLimpiarPotencia")
        self.label_30 = QtWidgets.QLabel(self.tab_8)
        self.label_30.setGeometry(QtCore.QRect(10, 100, 81, 16))
        self.label_30.setObjectName("label_30")
        self.pestanaPrincipal.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.label_31 = QtWidgets.QLabel(self.tab_9)
        self.label_31.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab_9)
        self.label_32.setGeometry(QtCore.QRect(10, 70, 16, 16))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_9)
        self.label_33.setGeometry(QtCore.QRect(10, 130, 21, 16))
        self.label_33.setObjectName("label_33")
        self.nDatoBinominal = QtWidgets.QLineEdit(self.tab_9)
        self.nDatoBinominal.setGeometry(QtCore.QRect(30, 70, 41, 20))
        self.nDatoBinominal.setObjectName("nDatoBinominal")
        self.rDatoBinominal = QtWidgets.QLineEdit(self.tab_9)
        self.rDatoBinominal.setGeometry(QtCore.QRect(30, 130, 41, 20))
        self.rDatoBinominal.setObjectName("rDatoBinominal")
        self.calcularBinominal = QtWidgets.QPushButton(self.tab_9)
        self.calcularBinominal.setGeometry(QtCore.QRect(10, 240, 75, 23))
        self.calcularBinominal.setObjectName("calcularBinominal")
        self.label_34 = QtWidgets.QLabel(self.tab_9)
        self.label_34.setGeometry(QtCore.QRect(10, 190, 21, 16))
        self.label_34.setObjectName("label_34")
        self.pDatoBinominal = QtWidgets.QLineEdit(self.tab_9)
        self.pDatoBinominal.setGeometry(QtCore.QRect(30, 190, 41, 20))
        self.pDatoBinominal.setObjectName("pDatoBinominal")
        self.label_35 = QtWidgets.QLabel(self.tab_9)
        self.label_35.setGeometry(QtCore.QRect(10, 50, 231, 16))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab_9)
        self.label_36.setGeometry(QtCore.QRect(10, 110, 141, 16))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab_9)
        self.label_37.setGeometry(QtCore.QRect(10, 170, 101, 16))
        self.label_37.setObjectName("label_37")
        self.groupBox = QtWidgets.QGroupBox(self.tab_9)
        self.groupBox.setGeometry(QtCore.QRect(250, 30, 441, 161))
        self.groupBox.setObjectName("groupBox")
        self.proceso1n = QtWidgets.QLineEdit(self.groupBox)
        self.proceso1n.setEnabled(False)
        self.proceso1n.setGeometry(QtCore.QRect(10, 90, 31, 20))
        self.proceso1n.setObjectName("proceso1n")
        self.proceso1x = QtWidgets.QLineEdit(self.groupBox)
        self.proceso1x.setEnabled(False)
        self.proceso1x.setGeometry(QtCore.QRect(10, 110, 31, 20))
        self.proceso1x.setObjectName("proceso1x")
        self.proceso1p = QtWidgets.QLineEdit(self.groupBox)
        self.proceso1p.setEnabled(False)
        self.proceso1p.setGeometry(QtCore.QRect(80, 110, 31, 20))
        self.proceso1p.setObjectName("proceso1p")
        self.proceso2x = QtWidgets.QLineEdit(self.groupBox)
        self.proceso2x.setEnabled(False)
        self.proceso2x.setGeometry(QtCore.QRect(130, 80, 31, 20))
        self.proceso2x.setObjectName("proceso2x")
        self.proceso3x = QtWidgets.QLineEdit(self.groupBox)
        self.proceso3x.setEnabled(False)
        self.proceso3x.setGeometry(QtCore.QRect(310, 80, 31, 20))
        self.proceso3x.setObjectName("proceso3x")
        self.proceso2n = QtWidgets.QLineEdit(self.groupBox)
        self.proceso2n.setEnabled(False)
        self.proceso2n.setGeometry(QtCore.QRect(250, 80, 31, 20))
        self.proceso2n.setObjectName("proceso2n")
        self.resultado2Binominal = QtWidgets.QLineEdit(self.groupBox)
        self.resultado2Binominal.setEnabled(False)
        self.resultado2Binominal.setGeometry(QtCore.QRect(350, 110, 81, 20))
        self.resultado2Binominal.setObjectName("resultado2Binominal")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(0, 90, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(70, 100, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(120, 100, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.proceso2p = QtWidgets.QLineEdit(self.groupBox)
        self.proceso2p.setEnabled(False)
        self.proceso2p.setGeometry(QtCore.QRect(200, 110, 31, 20))
        self.proceso2p.setObjectName("proceso2p")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(180, 110, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(290, 80, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(150, 100, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(240, 100, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(300, 110, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setGeometry(QtCore.QRect(40, 30, 16, 31))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(60, 30, 61, 31))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setGeometry(QtCore.QRect(30, 30, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setGeometry(QtCore.QRect(70, 30, 81, 16))
        self.label_24.setObjectName("label_24")
        self.label_14.raise_()
        self.label_18.raise_()
        self.label_13.raise_()
        self.proceso1p.raise_()
        self.proceso2x.raise_()
        self.proceso3x.raise_()
        self.proceso2n.raise_()
        self.resultado2Binominal.raise_()
        self.label_15.raise_()
        self.proceso1n.raise_()
        self.proceso1x.raise_()
        self.proceso2p.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_38 = QtWidgets.QLabel(self.tab_9)
        self.label_38.setGeometry(QtCore.QRect(250, 200, 151, 16))
        self.label_38.setObjectName("label_38")
        self.resultado1Binominal = QtWidgets.QLineEdit(self.tab_9)
        self.resultado1Binominal.setEnabled(False)
        self.resultado1Binominal.setGeometry(QtCore.QRect(252, 230, 151, 20))
        self.resultado1Binominal.setObjectName("resultado1Binominal")
        self.botonLimpiarBinominal = QtWidgets.QPushButton(self.tab_9)
        self.botonLimpiarBinominal.setGeometry(QtCore.QRect(420, 230, 75, 23))
        self.botonLimpiarBinominal.setObjectName("botonLimpiarBinominal")
        self.groupBox.raise_()
        self.label_31.raise_()
        self.label_32.raise_()
        self.label_33.raise_()
        self.nDatoBinominal.raise_()
        self.rDatoBinominal.raise_()
        self.calcularBinominal.raise_()
        self.label_34.raise_()
        self.pDatoBinominal.raise_()
        self.label_35.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.label_38.raise_()
        self.resultado1Binominal.raise_()
        self.botonLimpiarBinominal.raise_()
        self.pestanaPrincipal.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.label_39 = QtWidgets.QLabel(self.tab_10)
        self.label_39.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.tab_10)
        self.label_40.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.tab_10)
        self.label_41.setGeometry(QtCore.QRect(10, 120, 21, 16))
        self.label_41.setObjectName("label_41")
        self.datoXGeometrica = QtWidgets.QLineEdit(self.tab_10)
        self.datoXGeometrica.setGeometry(QtCore.QRect(30, 50, 41, 20))
        self.datoXGeometrica.setObjectName("datoXGeometrica")
        self.datoPGeometrica = QtWidgets.QLineEdit(self.tab_10)
        self.datoPGeometrica.setGeometry(QtCore.QRect(30, 120, 41, 20))
        self.datoPGeometrica.setObjectName("datoPGeometrica")
        self.label_42 = QtWidgets.QLabel(self.tab_10)
        self.label_42.setGeometry(QtCore.QRect(10, 90, 111, 16))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.tab_10)
        self.label_43.setGeometry(QtCore.QRect(180, 10, 161, 16))
        self.label_43.setObjectName("label_43")
        self.resultadoGeometrica = QtWidgets.QLineEdit(self.tab_10)
        self.resultadoGeometrica.setEnabled(False)
        self.resultadoGeometrica.setGeometry(QtCore.QRect(180, 40, 113, 20))
        self.resultadoGeometrica.setObjectName("resultadoGeometrica")
        self.botonCalcularGeometrica = QtWidgets.QPushButton(self.tab_10)
        self.botonCalcularGeometrica.setGeometry(QtCore.QRect(10, 160, 75, 23))
        self.botonCalcularGeometrica.setObjectName("botonCalcularGeometrica")
        self.botonLimpiarGeometrica = QtWidgets.QPushButton(self.tab_10)
        self.botonLimpiarGeometrica.setGeometry(QtCore.QRect(180, 80, 75, 23))
        self.botonLimpiarGeometrica.setObjectName("botonLimpiarGeometrica")
        self.pestanaPrincipal.addTab(self.tab_10, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label_44 = QtWidgets.QLabel(self.tab_7)
        self.label_44.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.tab_7)
        self.label_45.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.tab_7)
        self.label_46.setGeometry(QtCore.QRect(10, 80, 21, 16))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.tab_7)
        self.label_47.setGeometry(QtCore.QRect(10, 120, 121, 16))
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.tab_7)
        self.label_48.setGeometry(QtCore.QRect(10, 150, 21, 16))
        self.label_48.setObjectName("label_48")
        self.datoMPoisson = QtWidgets.QLineEdit(self.tab_7)
        self.datoMPoisson.setGeometry(QtCore.QRect(30, 80, 41, 20))
        self.datoMPoisson.setObjectName("datoMPoisson")
        self.datoNPoisson = QtWidgets.QLineEdit(self.tab_7)
        self.datoNPoisson.setGeometry(QtCore.QRect(30, 150, 41, 20))
        self.datoNPoisson.setObjectName("datoNPoisson")
        self.botonCalcularPoisson = QtWidgets.QPushButton(self.tab_7)
        self.botonCalcularPoisson.setGeometry(QtCore.QRect(10, 190, 75, 23))
        self.botonCalcularPoisson.setObjectName("botonCalcularPoisson")
        self.botonLimpiarPoisson = QtWidgets.QPushButton(self.tab_7)
        self.botonLimpiarPoisson.setGeometry(QtCore.QRect(280, 100, 75, 23))
        self.botonLimpiarPoisson.setObjectName("botonLimpiarPoisson")
        self.label_49 = QtWidgets.QLabel(self.tab_7)
        self.label_49.setGeometry(QtCore.QRect(280, 30, 151, 16))
        self.label_49.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_49.setObjectName("label_49")
        self.resultadoPoisson = QtWidgets.QLineEdit(self.tab_7)
        self.resultadoPoisson.setEnabled(False)
        self.resultadoPoisson.setGeometry(QtCore.QRect(280, 60, 251, 20))
        self.resultadoPoisson.setObjectName("resultadoPoisson")
        self.label_50 = QtWidgets.QLabel(self.tab_7)
        self.label_50.setGeometry(QtCore.QRect(490, 240, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.tab_7)
        self.label_51.setGeometry(QtCore.QRect(490, 220, 201, 16))
        self.label_51.setObjectName("label_51")
        self.pestanaPrincipal.addTab(self.tab_7, "")

        self.retranslateUi(ventanaPrincipal)
        self.pestanaPrincipal.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ventanaPrincipal)

    def retranslateUi(self, ventanaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        ventanaPrincipal.setWindowTitle(_translate("ventanaPrincipal", "Dialog"))
        self.label.setText(_translate("ventanaPrincipal", "Ingresa los datos"))
        self.label_2.setText(_translate("ventanaPrincipal", "Las permutaciones son:"))
        self.botonLimpiarPermutacion.setText(_translate("ventanaPrincipal", "Limpiar"))
        self.botonCalcularPermutacion.setText(_translate("ventanaPrincipal", "Permutación"))
        self.pestanaPrincipal.setTabText(self.pestanaPrincipal.indexOf(self.tab), _translate("ventanaPrincipal", "Permutación"))
        self.label_3.setText(_translate("ventanaPrincipal", "Ingresa el valor a calcular"))
        self.label_4.setText(_translate("ventanaPrincipal", "El factorial es :"))
        self.botonCalcularFactorial.setText(_translate("ventanaPrincipal", "Calcular"))
        self.botonLimpiarFactorial.setText(_translate("ventanaPrincipal", "Limpiar"))
        self.pestanaPrincipal.setTabText(self.pestanaPrincipal.indexOf(self.tab_2), _translate("ventanaPrincipal", "Factorial"))
        self.botonCalcularCombinacion.setText(_translate("ventanaPrincipal", "Combinar"))
        self.label_5.setText(_translate("ventanaPrincipal", "Las conbinaciones son :"))
        self.botonLimpiarCombinacion.setText(_translate("ventanaPrincipal", "Limpiar"))
        self.label_6.setText(_translate("ventanaPrincipal", "Ingresa los datos"))
        self.pestanaPrincipal.setTabText(self.pestanaPrincipal.indexOf(self.tab_3), _translate("ventanaPrincipal", "Combinación"))
        self.label_7.setText(_translate("ventanaPrincipal", "Ingresa la primera lista"))
        self.label_8.setText(_translate("ventanaPrincipal", "Ingresa la segunda lista"))
        self.botonCalcularUnion.setText(_translate("ventanaPrincipal", "Unión"))
        self.botonLimpiarUnion.setText(_translate("ventanaPrincipal", "Limpiar"))
        self.label_9.setText(_translate("ventanaPrincipal", "La union es :"))
        self.pestanaPrincipal.setTabText(self.pestanaPrincipal.indexOf(self.tab_4), _translate("ventanaPrincipal", "Unión"))
        self.botonLimpiarInterseccion.setText(_translate("ventanaPrincipal", "Limpiar"))
        self.label_10.setText(_translate("ventanaPrincipal", "Ingresa la segunda lista"))
        self.label_11.setText(_translate("ventanaPrincipal", "La interseccion es :"))
        self.botonCalcularInterseccion.setText(_translate("ventanaPrincipal", "Intersección"))
        self.label_12.setText(_translate("ventanaPrincipal", "Ingresa la primera lista"))
        self.pestanaPrincipal.setTabText(self.pestanaPrincipal.indexOf(self.tab_5), _translate("ventanaPrincipal", "Intersección"))
        self.botonCalcularDiferencia.setText(_translate("ventanaPrincipal", "Diferencia"))
        self.label_25.setText(_translate("ventanaPrincipal", "La diferencia es :"))
        self.label_26.setText(_translate("ventanaPrincipal", "Ingresa la segunda lista"))
        self.label_27.setText(_translate("ventanaPrincipal", "Ingresa la primera lista"))
        self.botonLimpiarDiferencia.setText(_translate("ventanaPrincipal", "Limpiar"))
        self.pestanaPrincipal.setTabText(self.pestanaPrincipal.indexOf(self.tab_6), _translate("ventanaPrincipal", "Diferencia"))
        self.label_28.setText(_translate("ventanaPrincipal", "Ingresa los datos"))
        self.label_29.setText(_translate("ventanaPrincipal", "elevar a la :"))
        self.botonCalcularPotencia.setText(_translate("ventanaPrincipal", "Potencia"))
        self.botonLimpiarPotencia.setText(_translate("ventanaPrincipal", "Limpiar"))
        self.label_30.setText(_translate("ventanaPrincipal", "La potencia es :"))
        self.pestanaPrincipal.setTabText(self.pestanaPrincipal.indexOf(self.tab_8), _translate("ventanaPrincipal", "Potencia"))
        self.label_31.setText(_translate("ventanaPrincipal", "Ingresa los datos"))
        self.label_32.setText(_translate("ventanaPrincipal", "n:"))
        self.label_33.setText(_translate("ventanaPrincipal", "x:"))
        self.calcularBinominal.setText(_translate("ventanaPrincipal", "Binominal"))
        self.label_34.setText(_translate("ventanaPrincipal", "p:"))
        self.label_35.setText(_translate("ventanaPrincipal", "Numero de veces que se repite el experimento"))
        self.label_36.setText(_translate("ventanaPrincipal", "Numero de exitos esperados"))
        self.label_37.setText(_translate("ventanaPrincipal", "Probabilidad de exito"))
        self.groupBox.setTitle(_translate("ventanaPrincipal", "Proceso distribución binominal"))
        self.label_13.setText(_translate("ventanaPrincipal", "(    )"))
        self.label_14.setText(_translate("ventanaPrincipal", "(     )"))
        self.label_15.setText(_translate("ventanaPrincipal", "^"))
        self.label_16.setText(_translate("ventanaPrincipal", "-"))
        self.label_17.setText(_translate("ventanaPrincipal", "-"))
        self.label_18.setText(_translate("ventanaPrincipal", "( 1         )"))
        self.label_19.setText(_translate("ventanaPrincipal", "^"))
        self.label_20.setText(_translate("ventanaPrincipal", "="))
        self.label_21.setText(_translate("ventanaPrincipal", "n \n"
"x"))
        self.label_22.setText(_translate("ventanaPrincipal", "(p)  (1 - p)"))
        self.label_23.setText(_translate("ventanaPrincipal", "(  )"))
        self.label_24.setText(_translate("ventanaPrincipal", "x           n - x"))
        self.label_38.setText(_translate("ventanaPrincipal", "La distribución binominal es :"))
        self.botonLimpiarBinominal.setText(_translate("ventanaPrincipal", "Limpiar"))
        self.pestanaPrincipal.setTabText(self.pestanaPrincipal.indexOf(self.tab_9), _translate("ventanaPrincipal", "Binominal"))
        self.label_39.setText(_translate("ventanaPrincipal", "Ingresa los datos"))
        self.label_40.setText(_translate("ventanaPrincipal", "x:"))
        self.label_41.setText(_translate("ventanaPrincipal", "p:"))
        self.label_42.setText(_translate("ventanaPrincipal", "Probabilidad de exito"))
        self.label_43.setText(_translate("ventanaPrincipal", "La distribuución geométrica es :"))
        self.botonCalcularGeometrica.setText(_translate("ventanaPrincipal", "Geométrica"))
        self.botonLimpiarGeometrica.setText(_translate("ventanaPrincipal", "Limpiar"))
        self.pestanaPrincipal.setTabText(self.pestanaPrincipal.indexOf(self.tab_10), _translate("ventanaPrincipal", "Geométrica"))
        self.label_44.setText(_translate("ventanaPrincipal", "Ingresa los datos"))
        self.label_45.setText(_translate("ventanaPrincipal", "Ingresa la media"))
        self.label_46.setText(_translate("ventanaPrincipal", "m:"))
        self.label_47.setText(_translate("ventanaPrincipal", "Numero de ocurrencias"))
        self.label_48.setText(_translate("ventanaPrincipal", "n:"))
        self.botonCalcularPoisson.setText(_translate("ventanaPrincipal", "Poisson"))
        self.botonLimpiarPoisson.setText(_translate("ventanaPrincipal", "Limpiar"))
        self.label_49.setText(_translate("ventanaPrincipal", "La distribución de poisson es :"))
        self.label_50.setText(_translate("ventanaPrincipal", "e=2.7182818284590452"))
        self.label_51.setText(_translate("ventanaPrincipal", "Numero de Euler usado en esta operación"))
        self.pestanaPrincipal.setTabText(self.pestanaPrincipal.indexOf(self.tab_7), _translate("ventanaPrincipal", "Poisson"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventanaPrincipal = QtWidgets.QDialog()
    ui = Ui_ventanaPrincipal()
    ui.setupUi(ventanaPrincipal)
    ventanaPrincipal.show()
    sys.exit(app.exec_())

